name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login Docker Hub
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.0.0
      id: buildx
    
    - name: Cache
      uses: actions/cache@v3.0.8
      with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

    - name: Filter
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          api-gateway:
            - 'apps/api-gateway/**'
            - 'libs/**'
          service-order:
            - 'apps/service-order/**'
            - 'libs/**'
          service-payment:
            - 'apps/service-payment/**'
            - 'libs/**'
    
    - name: Build and push api-gateway Docker image
      uses: docker/build-push-action@v3.1.1
      id: docker_build_api-gateway
      if: steps.filter.outputs.api-gateway == 'true'
      with:
          context: ./
          target: production
          file: ./apps/api-gateway/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/order-app/api-gateway
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          
    - name: Build and push service-order Docker image
      uses: docker/build-push-action@v3.1.1
      id: docker_build_service-order
      if: steps.filter.outputs.service-order == 'true'
      with:
          context: ./
          target: production
          file: ./apps/service-order/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/order-app/service-order
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          
    - name: Build and push service-payment Docker image
      uses: docker/build-push-action@v3.1.1
      id: docker_build_service-payment
      if: steps.filter.outputs.service-payment == 'true'
      with:
          context: ./
          target: production
          file: ./apps/service-payment/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/order-app/service-payment
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
